CREATE DATABASE Residencias;

USE Residencias;

CREATE TABLE CARRERAS (
  IDcarrera INTEGER(1) NOT NULL,
  Nombre VARCHAR(30) NOT NULL,
  PRIMARY KEY(IDcarrera)
)
TYPE=InnoDB;

CREATE TABLE CICLOS_ESCOLARES (
  IDCiclo INTEGER(3) NOT NULL,
  Descripcion VARCHAR(20) NOT NULL,
  PRIMARY KEY(IDCiclo)
)
TYPE=InnoDB;

CREATE TABLE EMPRESAS (
  IDEmpresa INTEGER(3) NOT NULL,
  RazonSocial VARCHAR(40) NOT NULL,
  Direccion VARCHAR(60) NULL,
  Telefono VARCHAR(15) NULL,
  Contacto VARCHAR(20) NULL,
  PRIMARY KEY(IDEmpresa)
)
TYPE=InnoDB;

CREATE TABLE ESTATUS_RESIDENCIAS (
  IDEstatus INTEGER(1) NOT NULL,
  Descripcion VARCHAR(20) NOT NULL,
  PRIMARY KEY(IDEstatus)
)
TYPE=InnoDB;

CREATE TABLE PROFESORES (
  IDProfesor INTEGER(3) NOT NULL,
  CURP VARCHAR(18) NULL,
  RFC VARCHAR(13) NULL,
  Nombre VARCHAR(35) NOT NULL,
  Correo VARCHAR(35) NULL,
  Celular VARCHAR(15) NULL,
  Usuario VARCHAR(18) NULL,
  Contrasenia VARCHAR(80) NULL,
  PRIMARY KEY(IDProfesor)
)
TYPE=InnoDB;

CREATE TABLE ALUMNOS (
  NumControl INTEGER(8) NOT NULL,
  IDCiclo INTEGER(3) NOT NULL,
  Nombre VARCHAR(30) NOT NULL,
  Correo VARCHAR(30) NOT NULL,
  Celular VARCHAR(18) NULL,
  Genero CHAR(1) NULL,
  IDCarrera INTEGER(1) NOT NULL,
  Direccion VARCHAR(30) NULL,
  TelFijo VARCHAR(18) NULL,
  PRIMARY KEY(NumControl)
)
TYPE=InnoDB;

CREATE TABLE ASESORES_EXTERNOS (
  IDAsesorEx INTEGER(2) NOT NULL,
  IDEmpresa INTEGER(3) NOT NULL,
  Nombre VARCHAR(30) NOT NULL,
  Cargo VARCHAR(20) NULL,
  Departamento VARCHAR(30) NULL,
  Correo INTEGER NULL,
  Telefono INTEGER NULL,
  PRIMARY KEY(IDAsesorEx)
)
TYPE=InnoDB;

CREATE TABLE RESIDENCIAS (
  NumControl INTEGER(8) NOT NULL,
  IDAsesorEx INTEGER(2) NOT NULL,
  Proyecto VARCHAR(180) NOT NULL,
  IDEstatus INTEGER(1) NOT NULL,
  IDProfesor INTEGER(3) NOT NULL,
  FechaInicio DATE NOT NULL,
  FechaTermino DATE NOT NULL,
  ConstanciaEmpresa CHAR(2) NULL,
  CandidatoTitulacion CHAR(2) NULL,
  PRIMARY KEY(NumControl)
)
TYPE=InnoDB;
